{"when":1724935941,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1724935941,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.109s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1724935941,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.015s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 23348/2260)"}
{"when":1724935941,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1724935941,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.716s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1724935942,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.749s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1724935942,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1724935942,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1724935943,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[7556:python.exe]"}
{"when":1724935963,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1724935963,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1724935964,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1724937121,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1724937121,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.115s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1724937121,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.016s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 17156/20816)"}
{"when":1724937121,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.017s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1724937121,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.398s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1724937122,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.710s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1724937122,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1724937122,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1724937122,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[6188:python.exe]"}
{"when":1724937123,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[6188:python.exe 20152:cmd.exe]"}
{"when":1724937123,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[6188:python.exe]"}
{"when":1724937138,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1724937138,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1724937139,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1724937215,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1724937215,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.111s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1724937215,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.016s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 16784/5728)"}
{"when":1724937215,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1724937216,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.372s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1724937216,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.688s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1724937216,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1724937216,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1724937217,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[17884:python.exe]"}
{"when":1724937232,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1724937232,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1724937234,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1724937300,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1724937300,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.123s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1724937300,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 15784/23400)"}
{"when":1724937300,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1724937300,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.398s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1724937301,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.713s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1724937301,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1724937301,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1724937302,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[6040:python.exe]"}
{"when":1724937317,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1724937317,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 0 ... map[]"}
{"when":1724937317,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1724937318,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1724937325,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1724937325,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.109s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1724937325,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.020s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 11824/22928)"}
{"when":1724937325,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1724937326,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.400s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1724937327,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.821s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1724937327,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1724937327,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1724937327,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[14296:python.exe]"}
{"when":1724937328,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[9064:cmd.exe 14296:python.exe]"}
{"when":1724937328,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[14296:python.exe]"}
{"when":1724937342,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[14296:python.exe 19748:node.exe]"}
{"when":1724937347,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 3 ... map[7472:chrome.exe 14296:python.exe 19748:node.exe]"}
{"when":1724937349,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 5 ... map[7472:chrome.exe 13300:chrome.exe 14296:python.exe 19748:node.exe 23368:chrome.exe]"}
{"when":1724937349,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[3308:chrome.exe 7472:chrome.exe 12392:chrome.exe 13300:chrome.exe 14296:python.exe 17776:chrome.exe 19748:node.exe 20688:chrome.exe 22988:chrome.exe 23368:chrome.exe]"}
{"when":1724937351,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 5 ... map[7472:chrome.exe 13300:chrome.exe 14296:python.exe 19748:node.exe 23368:chrome.exe]"}
{"when":1724937352,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 1 ... map[14296:python.exe]"}
{"when":1724937352,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1724937352,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1724937353,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1724938832,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1724938832,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.111s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1724938832,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 22716/22256)"}
{"when":1724938833,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1724938833,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.402s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1724938834,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.889s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1724938834,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1724938834,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1724938834,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[16512:python.exe]"}
{"when":1724938849,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[16512:python.exe 18852:node.exe]"}
{"when":1724938850,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 7 ... map[3952:chrome.exe 9172:chrome.exe 14116:chrome.exe 16512:python.exe 16956:chrome.exe 18852:node.exe 23260:chrome.exe]"}
{"when":1724938851,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 7 to 9 ... map[3952:chrome.exe 6288:chrome.exe 9172:chrome.exe 13832:chrome.exe 14116:chrome.exe 16512:python.exe 16956:chrome.exe 18852:node.exe 23260:chrome.exe]"}
{"when":1724938852,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 7 ... map[3952:chrome.exe 9172:chrome.exe 14116:chrome.exe 16512:python.exe 16956:chrome.exe 18852:node.exe 23260:chrome.exe]"}
{"when":1724938853,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 7 to 1 ... map[16512:python.exe]"}
{"when":1724938853,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1724938853,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1724938854,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725355033,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725355033,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.117s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725355033,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 19920/11096)"}
{"when":1725355033,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725355034,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.662s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725355035,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.886s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725355035,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725355035,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725355036,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[10920:python.exe]"}
{"when":1725355050,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725355050,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725355052,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725355288,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725355288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.100s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725355288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.020s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 16888/21352)"}
{"when":1725355288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725355288,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.325s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725355289,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.807s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725355289,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725355289,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725355289,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20492:python.exe]"}
{"when":1725355300,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725355300,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725355301,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725356101,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725356102,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.110s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725356102,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.021s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 4516/3220)"}
{"when":1725356102,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.018s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725356102,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.329s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725356103,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.774s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725356103,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725356103,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725356103,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[12412:python.exe]"}
{"when":1725356104,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725356104,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725356105,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725357017,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725357017,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.099s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725357017,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 18088/19628)"}
{"when":1725357017,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725357017,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.344s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725357018,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.821s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725357018,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725357018,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725357018,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[19752:python.exe]"}
{"when":1725357029,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[17712:node.exe 19752:python.exe]"}
{"when":1725357032,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 3 ... map[10064:chrome.exe 17712:node.exe 19752:python.exe]"}
{"when":1725357038,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 4 ... map[10064:chrome.exe 15976:chrome.exe 17712:node.exe 19752:python.exe]"}
{"when":1725357039,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 10 ... map[10064:chrome.exe 11400:chrome.exe 11600:chrome.exe 11640:chrome.exe 15976:chrome.exe 17712:node.exe 19752:python.exe 20040:chrome.exe 20864:chrome.exe 21156:chrome.exe]"}
{"when":1725357041,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[19752:python.exe]"}
{"when":1725357041,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725357041,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725357043,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725364266,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725364266,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.112s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725364266,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 2832/20052)"}
{"when":1725364266,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.022s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725364267,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.406s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725364267,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.697s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725364267,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725364267,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725364268,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22032:python.exe]"}
{"when":1725364279,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[22032:python.exe 24360:node.exe]"}
{"when":1725364280,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 5 ... map[2676:chrome.exe 12092:chrome.exe 22032:python.exe 24048:chrome.exe 24360:node.exe]"}
{"when":1725364281,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[2676:chrome.exe 4708:chrome.exe 12092:chrome.exe 15832:chrome.exe 18508:chrome.exe 22032:python.exe 24048:chrome.exe 24320:chrome.exe 24360:node.exe 24376:chrome.exe]"}
{"when":1725364283,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[22032:python.exe]"}
{"when":1725364283,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725364283,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725364284,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725364741,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725364741,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.119s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725364741,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.019s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 524/17024)"}
{"when":1725364741,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.023s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725364742,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.373s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725364742,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.658s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725364742,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725364742,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725364743,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22772:python.exe]"}
{"when":1725364754,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[22772:python.exe 24276:node.exe]"}
{"when":1725364754,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 8 ... map[2096:chrome.exe 2876:chrome.exe 10496:chrome.exe 13616:chrome.exe 17812:chrome.exe 22772:python.exe 22896:chrome.exe 24276:node.exe]"}
{"when":1725364755,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 8 to 10 ... map[2096:chrome.exe 2876:chrome.exe 8360:chrome.exe 10496:chrome.exe 13616:chrome.exe 17812:chrome.exe 22772:python.exe 22896:chrome.exe 23384:chrome.exe 24276:node.exe]"}
{"when":1725364761,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[22772:python.exe]"}
{"when":1725364761,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725364761,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725364762,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725365641,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725365641,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.108s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725365641,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.019s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 23096/24436)"}
{"when":1725365641,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725365641,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.358s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725365642,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.690s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725365642,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725365642,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725365643,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22652:python.exe]"}
{"when":1725365654,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[22652:python.exe 23364:node.exe]"}
{"when":1725365655,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 9 ... map[6752:chrome.exe 11712:chrome.exe 14920:chrome.exe 20092:chrome.exe 22652:python.exe 22796:chrome.exe 23364:node.exe 23928:chrome.exe 24084:chrome.exe]"}
{"when":1725365661,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[22652:python.exe]"}
{"when":1725365661,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725365661,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725365663,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725366530,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725366530,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.113s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725366530,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 24508/17588)"}
{"when":1725366530,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725366530,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.379s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725366531,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.658s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725366531,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725366531,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725366531,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[23740:python.exe]"}
{"when":1725366543,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725366543,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725366545,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725366559,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725366559,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.119s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725366559,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.023s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 24212/19528)"}
{"when":1725366559,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725366559,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.330s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725366560,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.655s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725366560,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725366560,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725366560,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[17568:python.exe]"}
{"when":1725366572,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[17568:python.exe 22008:node.exe]"}
{"when":1725366572,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 9 ... map[6020:chrome.exe 13964:chrome.exe 15428:chrome.exe 15976:chrome.exe 16976:chrome.exe 17568:python.exe 22008:node.exe 23808:chrome.exe 24152:chrome.exe]"}
{"when":1725366575,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 2 ... map[17568:python.exe 22008:node.exe]"}
{"when":1725366576,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725366576,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725366577,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725366617,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725366617,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.118s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725366617,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.020s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 23204/20924)"}
{"when":1725366617,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725366618,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.341s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725366618,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.652s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725366618,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725366618,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725366619,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[9100:python.exe]"}
{"when":1725366630,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[9100:python.exe 22548:node.exe]"}
{"when":1725366631,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 10 ... map[4336:chrome.exe 9100:python.exe 9444:chrome.exe 13760:chrome.exe 15172:chrome.exe 19912:chrome.exe 22548:node.exe 22860:chrome.exe 23712:chrome.exe 23756:chrome.exe]"}
{"when":1725366633,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 11 ... map[4336:chrome.exe 9100:python.exe 9444:chrome.exe 13760:chrome.exe 15172:chrome.exe 17512:chrome.exe 19912:chrome.exe 22548:node.exe 22860:chrome.exe 23712:chrome.exe 23756:chrome.exe]"}
{"when":1725366634,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 11 to 10 ... map[4336:chrome.exe 9100:python.exe 9444:chrome.exe 13760:chrome.exe 15172:chrome.exe 19912:chrome.exe 22548:node.exe 22860:chrome.exe 23712:chrome.exe 23756:chrome.exe]"}
{"when":1725366643,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 6 ... map[4336:chrome.exe 9100:python.exe 9444:chrome.exe 19912:chrome.exe 22548:node.exe 23712:chrome.exe]"}
{"when":1725366644,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725366644,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725366645,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725366866,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725366866,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.125s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725366866,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.019s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 19260/21816)"}
{"when":1725366866,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.031s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725366867,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.346s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725366867,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.612s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725366867,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725366867,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725366868,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20976:python.exe]"}
{"when":1725366878,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 4 ... map[3772:chrome.exe 17540:chrome.exe 20976:python.exe 22136:node.exe]"}
{"when":1725366879,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 9 ... map[3772:chrome.exe 12708:chrome.exe 14548:chrome.exe 17540:chrome.exe 19328:chrome.exe 20976:python.exe 22136:node.exe 23152:chrome.exe 23972:chrome.exe]"}
{"when":1725366891,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[20976:python.exe]"}
{"when":1725366892,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725366892,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725366893,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725367150,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725367150,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.101s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725367150,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.021s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 21128/13964)"}
{"when":1725367150,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.021s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725367151,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.335s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725367151,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.605s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725367151,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725367151,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725367152,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[23920:python.exe]"}
{"when":1725367162,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[22224:node.exe 23920:python.exe]"}
{"when":1725367162,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 8 ... map[13836:chrome.exe 18220:chrome.exe 21136:chrome.exe 22224:node.exe 22772:chrome.exe 23220:chrome.exe 23748:chrome.exe 23920:python.exe]"}
{"when":1725367163,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 8 to 10 ... map[11432:chrome.exe 13836:chrome.exe 18220:chrome.exe 21136:chrome.exe 22224:node.exe 22772:chrome.exe 23220:chrome.exe 23748:chrome.exe 23920:python.exe 24544:chrome.exe]"}
{"when":1725367175,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[23920:python.exe]"}
{"when":1725367175,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725367175,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725367177,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725367313,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725367313,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.119s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725367313,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.020s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 23772/17480)"}
{"when":1725367313,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.022s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725367313,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.319s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725367314,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.633s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725367314,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725367314,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725367314,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[12720:python.exe]"}
{"when":1725367324,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[12720:python.exe 21464:node.exe]"}
{"when":1725367325,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 7 ... map[2528:chrome.exe 2808:chrome.exe 3032:chrome.exe 12720:python.exe 17584:chrome.exe 21464:node.exe 23380:chrome.exe]"}
{"when":1725367326,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 7 to 9 ... map[2528:chrome.exe 2808:chrome.exe 3032:chrome.exe 12720:python.exe 17584:chrome.exe 19696:chrome.exe 21464:node.exe 23380:chrome.exe 23636:chrome.exe]"}
{"when":1725367359,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[12720:python.exe]"}
{"when":1725367359,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725367359,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725367360,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725367386,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725367386,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.116s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725367386,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.022s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 12180/22796)"}
{"when":1725367386,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.021s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725367387,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.320s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725367387,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.611s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725367387,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725367387,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725367387,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22476:python.exe]"}
{"when":1725367398,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 5 ... map[9888:chrome.exe 19696:node.exe 22476:python.exe 24024:chrome.exe 24128:chrome.exe]"}
{"when":1725367399,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[4384:chrome.exe 9888:chrome.exe 17088:chrome.exe 18644:chrome.exe 19116:chrome.exe 19696:node.exe 21396:chrome.exe 22476:python.exe 24024:chrome.exe 24128:chrome.exe]"}
{"when":1725367422,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[22476:python.exe]"}
{"when":1725367422,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725367422,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725367424,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725367794,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725367794,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.114s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725367794,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.021s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 21256/21188)"}
{"when":1725367794,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.018s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725367794,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.322s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725367795,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.624s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725367795,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725367795,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725367795,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22680:python.exe]"}
{"when":1725367806,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 5 ... map[17688:chrome.exe 20484:chrome.exe 22680:python.exe 23300:chrome.exe 23660:node.exe]"}
{"when":1725367806,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[11700:chrome.exe 15692:chrome.exe 17688:chrome.exe 17840:chrome.exe 20484:chrome.exe 22680:python.exe 22720:chrome.exe 23300:chrome.exe 23660:node.exe 24508:chrome.exe]"}
{"when":1725367810,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 5 ... map[17688:chrome.exe 20484:chrome.exe 22680:python.exe 23300:chrome.exe 23660:node.exe]"}
{"when":1725367810,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 1 ... map[22680:python.exe]"}
{"when":1725367810,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725367810,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725367812,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725368003,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725368003,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.115s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725368003,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.023s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 22032/15208)"}
{"when":1725368003,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.023s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725368004,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.333s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725368004,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.624s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725368004,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725368004,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725368005,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[18164:python.exe]"}
{"when":1725368016,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[4696:node.exe 18164:python.exe]"}
{"when":1725368016,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 10 ... map[4696:node.exe 9884:chrome.exe 12656:chrome.exe 18164:python.exe 19964:chrome.exe 20956:chrome.exe 22820:chrome.exe 23856:chrome.exe 23872:chrome.exe 24352:chrome.exe]"}
{"when":1725368020,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[18164:python.exe]"}
{"when":1725368021,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725368021,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725368022,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725368405,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725368405,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.130s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725368405,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.020s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 23748/19544)"}
{"when":1725368405,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.021s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725368405,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.331s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725368406,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.641s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725368406,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725368406,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725368406,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22796:python.exe]"}
{"when":1725368407,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725368407,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725368408,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725368711,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725368711,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.118s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725368711,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.021s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 9080/13952)"}
{"when":1725368711,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725368711,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.321s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725368712,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.631s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725368712,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725368712,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725368712,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[17624:python.exe]"}
{"when":1725368723,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 4 ... map[17104:chrome.exe 17624:python.exe 21944:node.exe 23304:chrome.exe]"}
{"when":1725368724,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 9 ... map[9140:chrome.exe 12088:chrome.exe 17104:chrome.exe 17624:python.exe 20544:chrome.exe 21944:node.exe 22876:chrome.exe 23204:chrome.exe 23304:chrome.exe]"}
{"when":1725368726,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 10 ... map[9140:chrome.exe 12088:chrome.exe 17104:chrome.exe 17604:chrome.exe 17624:python.exe 20544:chrome.exe 21944:node.exe 22876:chrome.exe 23204:chrome.exe 23304:chrome.exe]"}
{"when":1725368726,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 9 ... map[9140:chrome.exe 12088:chrome.exe 17104:chrome.exe 17624:python.exe 20544:chrome.exe 21944:node.exe 22876:chrome.exe 23204:chrome.exe 23304:chrome.exe]"}
{"when":1725368727,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 7 ... map[9140:chrome.exe 12088:chrome.exe 17104:chrome.exe 17624:python.exe 21944:node.exe 23204:chrome.exe 23304:chrome.exe]"}
{"when":1725368728,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 7 to 1 ... map[17624:python.exe]"}
{"when":1725368728,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725368728,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725368729,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725368823,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725368823,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.109s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725368823,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.016s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 22140/19764)"}
{"when":1725368823,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.021s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725368823,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.316s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725368824,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.615s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725368824,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725368824,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725368824,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[17844:python.exe]"}
{"when":1725368835,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[16676:node.exe 17844:python.exe]"}
{"when":1725368835,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 9 ... map[12204:chrome.exe 15716:chrome.exe 16676:node.exe 17844:python.exe 22584:chrome.exe 23056:chrome.exe 23800:chrome.exe 23952:chrome.exe 24056:chrome.exe]"}
{"when":1725368840,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[17844:python.exe]"}
{"when":1725368840,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725368840,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725368841,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725368862,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725368863,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.113s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725368863,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 24572/20992)"}
{"when":1725368863,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725368863,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.349s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725368864,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.645s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725368864,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725368864,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725368864,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[5232:python.exe]"}
{"when":1725368874,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[5232:python.exe 16756:node.exe]"}
{"when":1725368875,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 8 ... map[1040:chrome.exe 5232:python.exe 6292:chrome.exe 13744:chrome.exe 16756:node.exe 19124:chrome.exe 22224:chrome.exe 24508:chrome.exe]"}
{"when":1725368875,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 8 to 10 ... map[1040:chrome.exe 5232:python.exe 6292:chrome.exe 12460:chrome.exe 13744:chrome.exe 16756:node.exe 19124:chrome.exe 22224:chrome.exe 23284:chrome.exe 24508:chrome.exe]"}
{"when":1725368879,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 2 ... map[5232:python.exe 16756:node.exe]"}
{"when":1725368879,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725368879,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725368880,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725368916,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725368916,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.112s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725368916,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 20412/11440)"}
{"when":1725368916,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725368917,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.329s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725368917,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.633s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725368917,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725368917,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725368917,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22128:python.exe]"}
{"when":1725368928,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 6 ... map[524:chrome.exe 3744:node.exe 11112:chrome.exe 22128:python.exe 23092:chrome.exe 23128:chrome.exe]"}
{"when":1725368929,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 6 to 9 ... map[524:chrome.exe 3744:node.exe 11112:chrome.exe 17088:chrome.exe 21160:chrome.exe 22128:python.exe 23092:chrome.exe 23128:chrome.exe 23844:chrome.exe]"}
{"when":1725368932,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 2 ... map[3744:node.exe 22128:python.exe]"}
{"when":1725368933,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725368933,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725368934,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725368992,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725368992,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.113s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725368992,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 23868/24296)"}
{"when":1725368992,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725368992,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.341s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725368993,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.617s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725368993,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725368993,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725368993,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[24248:python.exe]"}
{"when":1725369003,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[17000:node.exe 24248:python.exe]"}
{"when":1725369004,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 8 ... map[1876:chrome.exe 10552:chrome.exe 11400:chrome.exe 17000:node.exe 18164:chrome.exe 21360:chrome.exe 23716:chrome.exe 24248:python.exe]"}
{"when":1725369005,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 8 to 10 ... map[1876:chrome.exe 8556:chrome.exe 10552:chrome.exe 11400:chrome.exe 14884:chrome.exe 17000:node.exe 18164:chrome.exe 21360:chrome.exe 23716:chrome.exe 24248:python.exe]"}
{"when":1725369039,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[24248:python.exe]"}
{"when":1725369039,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725369039,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725369040,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725369563,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725369563,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.124s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725369563,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.016s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 14924/22700)"}
{"when":1725369563,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.022s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725369564,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.326s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725369564,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.638s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725369564,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725369564,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725369565,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[6428:python.exe]"}
{"when":1725369575,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 4 ... map[6428:python.exe 13920:node.exe 21968:chrome.exe 22772:chrome.exe]"}
{"when":1725369576,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 9 ... map[6428:python.exe 11620:chrome.exe 13920:node.exe 19340:chrome.exe 19772:chrome.exe 21968:chrome.exe 21972:chrome.exe 22772:chrome.exe 24292:chrome.exe]"}
{"when":1725369579,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 4 ... map[6428:python.exe 13920:node.exe 21968:chrome.exe 22772:chrome.exe]"}
{"when":1725369579,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725369579,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725369581,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725370396,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725370396,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.108s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725370396,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.020s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 10988/14092)"}
{"when":1725370397,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725370397,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.352s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725370398,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.680s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725370398,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725370398,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725370398,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[17848:python.exe]"}
{"when":1725370409,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[10752:chrome.exe 15832:node.exe 17848:python.exe]"}
{"when":1725370410,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 10 ... map[5292:chrome.exe 6976:chrome.exe 10752:chrome.exe 14840:chrome.exe 15260:chrome.exe 15832:node.exe 17848:python.exe 20332:chrome.exe 22792:chrome.exe 24460:chrome.exe]"}
{"when":1725370455,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[17848:python.exe]"}
{"when":1725370455,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725370455,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725370456,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725370577,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725370577,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.104s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725370577,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.019s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 2692/5292)"}
{"when":1725370577,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725370577,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.338s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725370578,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.625s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725370578,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725370578,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725370578,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[21120:python.exe]"}
{"when":1725370591,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[5112:node.exe 21120:python.exe]"}
{"when":1725370594,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 3 ... map[5112:node.exe 21120:python.exe 23128:chrome.exe]"}
{"when":1725370595,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 9 ... map[5112:node.exe 5692:chrome.exe 9068:chrome.exe 16828:chrome.exe 20168:chrome.exe 21120:python.exe 22380:chrome.exe 23128:chrome.exe 24996:chrome.exe]"}
{"when":1725370597,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 10 ... map[5112:node.exe 5692:chrome.exe 9068:chrome.exe 16828:chrome.exe 18180:chrome.exe 20168:chrome.exe 21120:python.exe 22380:chrome.exe 23128:chrome.exe 24996:chrome.exe]"}
{"when":1725370598,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 9 ... map[5112:node.exe 5692:chrome.exe 9068:chrome.exe 16828:chrome.exe 20168:chrome.exe 21120:python.exe 22380:chrome.exe 23128:chrome.exe 24996:chrome.exe]"}
{"when":1725370640,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[21120:python.exe]"}
{"when":1725370640,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725370640,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725370641,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725371236,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725371236,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.109s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725371236,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 24588/5096)"}
{"when":1725371236,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725371236,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.348s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725371237,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.634s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725371237,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725371237,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725371237,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[24228:python.exe]"}
{"when":1725371248,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[23284:node.exe 24228:python.exe]"}
{"when":1725371248,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 5 ... map[3440:chrome.exe 4608:chrome.exe 10516:chrome.exe 23284:node.exe 24228:python.exe]"}
{"when":1725371249,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[3440:chrome.exe 4608:chrome.exe 9624:chrome.exe 10516:chrome.exe 20456:chrome.exe 20968:chrome.exe 23284:node.exe 23744:chrome.exe 23788:chrome.exe 24228:python.exe]"}
{"when":1725371251,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 11 ... map[3440:chrome.exe 4608:chrome.exe 9624:chrome.exe 10516:chrome.exe 20456:chrome.exe 20968:chrome.exe 22716:chrome.exe 23284:node.exe 23744:chrome.exe 23788:chrome.exe 24228:python.exe]"}
{"when":1725371252,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 11 to 10 ... map[3440:chrome.exe 4608:chrome.exe 9624:chrome.exe 10516:chrome.exe 20456:chrome.exe 20968:chrome.exe 23284:node.exe 23744:chrome.exe 23788:chrome.exe 24228:python.exe]"}
{"when":1725371359,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[24228:python.exe]"}
{"when":1725371359,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725371360,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725371361,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725454456,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725454456,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.108s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725454456,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.019s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 12212/19220)"}
{"when":1725454456,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.024s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725454457,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.660s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725454458,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.727s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725454458,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725454458,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725454458,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[20800:python.exe]"}
{"when":1725454458,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[17664:cmd.exe 20800:python.exe]"}
{"when":1725454459,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 1 ... map[20800:python.exe]"}
{"when":1725454472,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[7460:node.exe 20800:python.exe]"}
{"when":1725454475,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 3 ... map[7460:node.exe 10560:chrome.exe 20800:python.exe]"}
{"when":1725454476,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 9 ... map[7460:node.exe 10560:chrome.exe 13056:chrome.exe 19416:chrome.exe 20372:chrome.exe 20800:python.exe 21528:chrome.exe 21752:chrome.exe 21764:chrome.exe]"}
{"when":1725454578,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[20800:python.exe]"}
{"when":1725454578,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725454578,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725454579,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725455160,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725455161,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.116s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725455161,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.020s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 20816/19340)"}
{"when":1725455161,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725455161,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.338s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725455162,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.637s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725455162,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725455162,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725455162,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[21652:python.exe]"}
{"when":1725455173,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[20100:node.exe 21652:python.exe 22352:chrome.exe]"}
{"when":1725455173,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 9 ... map[1168:chrome.exe 1864:chrome.exe 12640:chrome.exe 14736:chrome.exe 20100:node.exe 20848:chrome.exe 21424:chrome.exe 21652:python.exe 22352:chrome.exe]"}
{"when":1725455174,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[21652:python.exe]"}
{"when":1725455175,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725455175,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725455176,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725455234,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725455234,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.110s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725455234,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 21292/20424)"}
{"when":1725455234,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.017s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725455235,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.311s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725455235,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.625s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725455235,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725455235,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725455235,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[9816:python.exe]"}
{"when":1725455246,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[9816:python.exe 22940:node.exe]"}
{"when":1725455246,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 10 ... map[3604:chrome.exe 9816:python.exe 14940:chrome.exe 15624:chrome.exe 18480:chrome.exe 20172:chrome.exe 21596:chrome.exe 21624:chrome.exe 22456:chrome.exe 22940:node.exe]"}
{"when":1725455349,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 8 ... map[3604:chrome.exe 9816:python.exe 14940:chrome.exe 18480:chrome.exe 20172:chrome.exe 21596:chrome.exe 22456:chrome.exe 22940:node.exe]"}
{"when":1725455349,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725455349,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725455350,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725456388,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725456388,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.112s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725456388,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.021s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 20316/20276)"}
{"when":1725456388,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.018s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725456388,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.326s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725456389,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.622s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725456389,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725456389,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725456389,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[21172:python.exe]"}
{"when":1725456400,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[20228:chrome.exe 21172:python.exe 23116:node.exe]"}
{"when":1725456401,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 9 ... map[5480:chrome.exe 18684:chrome.exe 19340:chrome.exe 19748:chrome.exe 20228:chrome.exe 21172:python.exe 21736:chrome.exe 23116:node.exe 23492:chrome.exe]"}
{"when":1725456402,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[21172:python.exe]"}
{"when":1725456402,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725456402,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725456403,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725456428,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725456428,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.104s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725456428,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.016s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 20220/23532)"}
{"when":1725456428,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725456429,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.326s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725456429,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.618s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725456429,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725456429,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725456429,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[5364:python.exe]"}
{"when":1725456430,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725456430,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725456431,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725456481,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725456481,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.121s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725456481,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.016s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 15428/21196)"}
{"when":1725456481,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725456481,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.316s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725456482,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.647s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725456482,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725456482,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725456482,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[1888:python.exe]"}
{"when":1725456493,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[1888:python.exe 10692:node.exe]"}
{"when":1725456494,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 7 ... map[1888:python.exe 2344:chrome.exe 10692:node.exe 14828:chrome.exe 15520:chrome.exe 16844:chrome.exe 18656:chrome.exe]"}
{"when":1725456494,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 7 to 9 ... map[1888:python.exe 2344:chrome.exe 10692:node.exe 14828:chrome.exe 15520:chrome.exe 16844:chrome.exe 18656:chrome.exe 21464:chrome.exe 23040:chrome.exe]"}
{"when":1725456525,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 7 ... map[1888:python.exe 2344:chrome.exe 10692:node.exe 14828:chrome.exe 15520:chrome.exe 16844:chrome.exe 18656:chrome.exe]"}
{"when":1725456526,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725456526,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 7 to 0 ... map[]"}
{"when":1725456526,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725456526,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725457834,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725457835,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.117s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725457835,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.019s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 21104/3044)"}
{"when":1725457835,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725457835,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.335s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725457836,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.670s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725457836,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725457836,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725457836,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[1428:python.exe]"}
{"when":1725457848,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[1428:python.exe 20476:node.exe]"}
{"when":1725457848,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 4 ... map[1428:python.exe 2948:chrome.exe 20416:chrome.exe 20476:node.exe]"}
{"when":1725457849,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 9 ... map[1428:python.exe 2948:chrome.exe 10804:chrome.exe 16868:chrome.exe 20416:chrome.exe 20476:node.exe 20668:chrome.exe 22784:chrome.exe 22880:chrome.exe]"}
{"when":1725457948,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[1428:python.exe]"}
{"when":1725457948,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725457948,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725457949,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725458302,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725458302,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.119s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725458302,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.019s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 22068/9908)"}
{"when":1725458302,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.017s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725458302,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.343s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725458303,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.628s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725458303,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725458303,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725458303,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[5124:python.exe]"}
{"when":1725458314,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 5 ... map[148:chrome.exe 5124:python.exe 8380:chrome.exe 15500:chrome.exe 22932:node.exe]"}
{"when":1725458314,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[148:chrome.exe 5124:python.exe 8380:chrome.exe 15500:chrome.exe 17604:chrome.exe 19548:chrome.exe 19888:chrome.exe 19968:chrome.exe 22596:chrome.exe 22932:node.exe]"}
{"when":1725458344,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 12 ... map[148:chrome.exe 5124:python.exe 8380:chrome.exe 15500:chrome.exe 17604:chrome.exe 19548:chrome.exe 19888:chrome.exe 19968:chrome.exe 21752:chrome.exe 22596:chrome.exe 22932:node.exe 23280:chrome.exe]"}
{"when":1725458344,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 12 to 10 ... map[148:chrome.exe 5124:python.exe 8380:chrome.exe 15500:chrome.exe 17604:chrome.exe 19548:chrome.exe 19888:chrome.exe 19968:chrome.exe 22596:chrome.exe 22932:node.exe]"}
{"when":1725458430,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 8 ... map[148:chrome.exe 5124:python.exe 8380:chrome.exe 15500:chrome.exe 19888:chrome.exe 19968:chrome.exe 22596:chrome.exe 22932:node.exe]"}
{"when":1725458430,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 8 to 1 ... map[5124:python.exe]"}
{"when":1725458430,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725458430,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725458432,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725529334,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725529334,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.114s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725529334,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 20552/12200)"}
{"when":1725529334,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.017s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725529335,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.644s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725529335,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.678s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725529335,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725529335,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725529336,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[5020:python.exe]"}
{"when":1725529351,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[5020:python.exe 10868:node.exe]"}
{"when":1725529354,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 3 ... map[5020:python.exe 10868:node.exe 19960:chrome.exe]"}
{"when":1725529354,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 5 ... map[5020:python.exe 10868:node.exe 15660:chrome.exe 19960:chrome.exe 22016:chrome.exe]"}
{"when":1725529355,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[4708:chrome.exe 5020:python.exe 6432:chrome.exe 7284:chrome.exe 10868:node.exe 15660:chrome.exe 19808:chrome.exe 19960:chrome.exe 20136:chrome.exe 22016:chrome.exe]"}
{"when":1725529451,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 8 ... map[4708:chrome.exe 5020:python.exe 7284:chrome.exe 10868:node.exe 15660:chrome.exe 19960:chrome.exe 20136:chrome.exe 22016:chrome.exe]"}
{"when":1725529452,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725529452,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725529453,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725529972,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725529972,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.110s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725529972,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 4876/22692)"}
{"when":1725529972,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.019s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725529973,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.329s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725529973,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.626s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725529973,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725529973,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725529973,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[21632:python.exe]"}
{"when":1725529985,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[16536:node.exe 21632:python.exe]"}
{"when":1725529985,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 10 ... map[4868:chrome.exe 5012:chrome.exe 14048:chrome.exe 15832:chrome.exe 16536:node.exe 16936:chrome.exe 21512:chrome.exe 21632:python.exe 22368:chrome.exe 22932:chrome.exe]"}
{"when":1725530071,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[21632:python.exe]"}
{"when":1725530071,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725530071,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725530072,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725539935,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725539935,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.110s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725539935,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 19960/6100)"}
{"when":1725539935,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.016s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725539936,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.377s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725539937,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.874s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725539937,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725539937,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725539937,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[1824:python.exe]"}
{"when":1725539948,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[1824:python.exe 24528:node.exe]"}
{"when":1725539951,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 4 ... map[1824:python.exe 9848:chrome.exe 13216:chrome.exe 24528:node.exe]"}
{"when":1725539952,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 9 ... map[1824:python.exe 5468:chrome.exe 9848:chrome.exe 13216:chrome.exe 16076:chrome.exe 21260:chrome.exe 21972:chrome.exe 23480:chrome.exe 24528:node.exe]"}
{"when":1725539955,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[1824:python.exe]"}
{"when":1725539955,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725539955,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725539956,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725539988,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725539988,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.107s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725539988,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 24436/22652)"}
{"when":1725539988,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.017s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725539989,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.313s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725539990,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.879s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725539990,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725539990,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725539990,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[22076:python.exe]"}
{"when":1725540001,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 5 ... map[6072:chrome.exe 17044:chrome.exe 22076:python.exe 22560:node.exe 23304:chrome.exe]"}
{"when":1725540001,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 10 ... map[3208:chrome.exe 3440:chrome.exe 4328:chrome.exe 6072:chrome.exe 17044:chrome.exe 21936:chrome.exe 22076:python.exe 22560:node.exe 22708:chrome.exe 23304:chrome.exe]"}
{"when":1725540094,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[22076:python.exe]"}
{"when":1725540095,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725540095,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725540096,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725541352,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725541352,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.101s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725541352,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 24992/23140)"}
{"when":1725541352,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.016s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725541352,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.365s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725541353,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.900s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725541353,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725541353,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725541354,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[5560:python.exe]"}
{"when":1725541364,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 3 ... map[5560:python.exe 10896:chrome.exe 21540:node.exe]"}
{"when":1725541365,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 3 to 10 ... map[5560:python.exe 10896:chrome.exe 21016:chrome.exe 21540:node.exe 22264:chrome.exe 22636:chrome.exe 23180:chrome.exe 24688:chrome.exe 25112:chrome.exe 25412:chrome.exe]"}
{"when":1725541368,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 11 ... map[1492:chrome.exe 5560:python.exe 10896:chrome.exe 21016:chrome.exe 21540:node.exe 22264:chrome.exe 22636:chrome.exe 23180:chrome.exe 24688:chrome.exe 25112:chrome.exe 25412:chrome.exe]"}
{"when":1725541368,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 11 to 10 ... map[5560:python.exe 10896:chrome.exe 21016:chrome.exe 21540:node.exe 22264:chrome.exe 22636:chrome.exe 23180:chrome.exe 24688:chrome.exe 25112:chrome.exe 25412:chrome.exe]"}
{"when":1725541461,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[5560:python.exe]"}
{"when":1725541462,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725541462,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725541463,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725542145,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725542145,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.110s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725542145,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.016s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 25484/2688)"}
{"when":1725542145,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.020s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725542146,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.334s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725542147,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.960s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725542147,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725542147,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725542147,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[23968:python.exe]"}
{"when":1725542158,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 4 ... map[10692:node.exe 22936:chrome.exe 23956:chrome.exe 23968:python.exe]"}
{"when":1725542158,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 4 to 10 ... map[10692:node.exe 16208:chrome.exe 18360:chrome.exe 19492:chrome.exe 19932:chrome.exe 20584:chrome.exe 22936:chrome.exe 23720:chrome.exe 23956:chrome.exe 23968:python.exe]"}
{"when":1725542260,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[23968:python.exe]"}
{"when":1725542261,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725542261,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725542262,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725542494,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725542495,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.106s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725542495,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 16920/4976)"}
{"when":1725542495,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.022s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725542495,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.316s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725542496,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.857s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725542496,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725542496,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725542496,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[7268:python.exe]"}
{"when":1725542506,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[7268:python.exe 18360:node.exe]"}
{"when":1725542507,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 5 ... map[7268:python.exe 13880:chrome.exe 18360:node.exe 25368:chrome.exe 25436:chrome.exe]"}
{"when":1725542507,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 5 to 9 ... map[7268:python.exe 13880:chrome.exe 16536:chrome.exe 18360:node.exe 21464:chrome.exe 21584:chrome.exe 25368:chrome.exe 25436:chrome.exe 25528:chrome.exe]"}
{"when":1725542513,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[7268:python.exe]"}
{"when":1725542513,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was FAILURE, reason: exit status 1","comment":"rcc point of view"}
{"when":1725542513,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725542514,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725542601,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725542601,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.113s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725542601,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.018s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 19116/18360)"}
{"when":1725542601,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.022s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725542601,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.322s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725542602,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.873s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725542602,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725542602,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725542603,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[23808:python.exe]"}
{"when":1725542613,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[5560:node.exe 23808:python.exe]"}
{"when":1725542614,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 10 ... map[5560:node.exe 13916:chrome.exe 15888:chrome.exe 17780:chrome.exe 19788:chrome.exe 21852:chrome.exe 22080:chrome.exe 22260:chrome.exe 23808:python.exe 25092:chrome.exe]"}
{"when":1725542722,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 1 ... map[23808:python.exe]"}
{"when":1725542723,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725542723,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725542724,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
{"when":1725543945,"controller":"rcc.robocorpcode","event":"start task","detail":"name=Run Task from=c:\\Robocorp\\order-robot-python\\robot.yaml","comment":"at task environment setup"}
{"when":1725543945,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 00/15 v17.28.4 0.107s Context: \"AgnieszkaRadomska\" \u003cAzureAD\\AgnieszkaRadomska@5CG2163J0J\u003e [windows_amd64/Microsoft Windows [Version 10.0.19045.4780]]."}
{"when":1725543945,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 01/15 v17.28.4 0.017s Fresh [shared mode] holotree environment c28a4522-82e4-ef0d-8b5d-e1774b62c046. (parent/pid: 6152/5728)"}
{"when":1725543945,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 02/15 v17.28.4 0.017s Holotree blueprint is \"5693ac85742e7335\" [windows_amd64 with 7 workers on 8 CPUs from \"conda.yaml\"]."}
{"when":1725543946,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 14/15 v17.28.4 0.339s Restore space from library [with 7 workers on 8 CPUs; with compression: true]."}
{"when":1725543947,"controller":"rcc.robocorpcode","event":"environment","detail":"build","comment":"Progress: 15/15 v17.28.4 0.866s Fresh holotree done [with 7 workers on 8 CPUs]."}
{"when":1725543947,"controller":"rcc.robocorpcode","event":"start","detail":"robot","comment":"started"}
{"when":1725543947,"controller":"rcc.robocorpcode","event":"run","detail":"robot","comment":"task run"}
{"when":1725543947,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 0 to 1 ... map[25052:python.exe]"}
{"when":1725543960,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 1 to 2 ... map[19836:node.exe 25052:python.exe]"}
{"when":1725543963,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 2 to 8 ... map[19836:node.exe 20840:chrome.exe 22816:chrome.exe 23888:chrome.exe 24120:chrome.exe 24580:chrome.exe 25052:python.exe 25056:chrome.exe]"}
{"when":1725543964,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 8 to 10 ... map[19836:node.exe 20840:chrome.exe 20952:chrome.exe 22816:chrome.exe 23888:chrome.exe 24120:chrome.exe 24580:chrome.exe 24808:chrome.exe 25052:python.exe 25056:chrome.exe]"}
{"when":1725543967,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 11 ... map[19836:node.exe 20840:chrome.exe 20952:chrome.exe 22816:chrome.exe 23888:chrome.exe 24120:chrome.exe 24580:chrome.exe 24808:chrome.exe 25052:python.exe 25056:chrome.exe 25312:chrome.exe]"}
{"when":1725543967,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 11 to 10 ... map[19836:node.exe 20840:chrome.exe 20952:chrome.exe 22816:chrome.exe 23888:chrome.exe 24120:chrome.exe 24580:chrome.exe 24808:chrome.exe 25052:python.exe 25056:chrome.exe]"}
{"when":1725544061,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 10 to 9 ... map[19836:node.exe 20840:chrome.exe 20952:chrome.exe 22816:chrome.exe 23888:chrome.exe 24120:chrome.exe 24580:chrome.exe 25052:python.exe 25056:chrome.exe]"}
{"when":1725544062,"controller":"rcc.robocorpcode","event":"processes","detail":"updated","comment":"count from 9 to 1 ... map[25052:python.exe]"}
{"when":1725544062,"controller":"rcc.robocorpcode","event":"robot exit","detail":"From rcc \"v17.28.4\" (controller: \"RobocorpCode\") point of view, \"actual main robot run\" was SUCCESS.","comment":"rcc point of view"}
{"when":1725544062,"controller":"rcc.robocorpcode","event":"processes","detail":"final","comment":"count: 0"}
{"when":1725544063,"controller":"rcc.robocorpcode","event":"stop","detail":"robot","comment":"done"}
